### ISSUE TITLE
Unhandled rejection TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by endiliey** [themgoncalves/react-loadable-ssr-addon#11]
# Issue Title
Bug caused due to 0.1.7 from https://github.com/themgoncalves/react-loadable-ssr-addon/commit/6c18c7ae07074cc25a2889e5c9a4b97acab807d1

## Expected Behavior
No error

## Current Behavior
```bash
Unhandled rejection TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:1168:7)
    at ReactLoadableSSRAddon.get (/home/travis/build/endiliey/endiliey.github.io/website/node_modules/react-loadable-ssr-addon/lib/ReactLoadableSSRAddon.js:246:31)
    at ReactLoadableSSRAddon.writeAssetsFile (/home/travis/build/endiliey/endiliey.github.io/website/node_modules/react-loadable-ssr-addon/lib/ReactLoadableSSRAddon.js:189:25)
```

## Possible Solution

I think filename should not be defined here.
https://github.com/themgoncalves/react-loadable-ssr-addon/blob/6c18c7ae07074cc25a2889e5c9a4b97acab807d1/source/ReactLoadableSSRAddon.js#L67

It should be 
```js
const filename = this.options.filename
```

This is the line that causes the error
https://github.com/themgoncalves/react-loadable-ssr-addon/blob/6c18c7ae07074cc25a2889e5c9a4b97acab807d1/source/ReactLoadableSSRAddon.js#L80

Previously it was
https://github.com/themgoncalves/react-loadable-ssr-addon/blob/7b8721db4da23fed0657e5b1755014b7f5daaf62/source/ReactLoadableSSRAddon.js#L142

I can submit a PR

**Comment by themgoncalves** [comment]
@endiliey thanks for spotting that and create a fix in PR #12 💪
